# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
   include:
    - M365ConfigWithCert.ps1
pool:
  name: Microsoft365Dsc
steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'AVANADELAB - DEMO'
    KeyVaultName: 'M365Secret'
    SecretsFilter: 'M365OrgName,M365TenantId,M365ApplicationId,M365ClientCertificateThumbPrint'
    RunAsPreJob: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      .\M365ConfigWithCert.ps1 -OrgName $(M365OrgName) -TenantId $(M365TenantId) -ApplicationId $(M365ApplicationId) -CertificateId $(M365ClientCertificateThumbPrint)
- task: CopyFiles@2
  displayName: 'Copy Files Build Folder'
  inputs:
    SourceFolder: .
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Package'
  inputs:
    ArtifactName: 'M365DSC-Config'