# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
   include:
    - M365Config.ps1
pool:
  vmImage: 'windows-2022'
  name: Azure Pipelines
steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'M365DSC-AVANADELAB'
    KeyVaultName: 'M365Secret'
    SecretsFilter: 'username,password'
    RunAsPreJob: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      winrm quickconfig -force
      Install-Module 'Microsoft365DSC' -Force
      .\M365Config.ps1 -AdminCredential $(username) -AdminPassword $(password)
- task: CopyFiles@2
  displayName: 'Copy Files Build Folder'
  inputs:
    SourceFolder: .
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Package'
  inputs:
    ArtifactName: 'M365DSC-Config'